### ISSUE TITLE
Incorrect httpStatus code: ibm-wave5-I2PS/idea-hub-service/src/main/java/com/stackroute/controller/IdeaHubController.java

### ISSUE THREAD

**Issue by sushmitha007** [stackroute/ibm-wave5-I2PS#39]
catch (Exception e)
        {
            e.getMessage();
             responseEntity=new ResponseEntity("Something went wrong",HttpStatus.CONFLICT);

        }
        return responseEntity;

**Comment by GargiLaha** [comment]
Used BAD_REQUEST error code. 

catch (Exception e)
{
e.getMessage();
responseEntity=new ResponseEntity("Something went wrong",HttpStatus.BAD_REQUEST);

    }
    return responseEntity;
